set lpsolve "D:\AutoCellLibX\tools\gurobi_cl\gurobi_cl.cmd"
load technology "D:\AutoCellLibX\tools\astran\build\Work\tech_freePDK45.rul"
load netlist "D:\AutoCellLibX\flow\outputs\adder\COMPLEX11.sp"
set rowheight 13
set grid 0.19 0.19
set supplysize 0.26
set nwellpos 1.235
set celltemplate "Tapless"
cellgen select COMPLEX11
cellgen autoflow
export layout COMPLEX11 D:\AutoCellLibX\flow\outputs\adder/COMPLEX11.gds
exit

