set lpsolve "D:\AutoCellLibX\tools\gurobi_cl\gurobi_cl.cmd"
load technology "D:\AutoCellLibX\tools\astran\build\Work\tech_freePDK45.rul"
load netlist "D:\AutoCellLibX\pySrc\outputs\adder\COMPLEX10.sp"
set rowheight 13
set grid 0.19 0.19
set supplysize 0.26
set nwellpos 1.0825
set celltemplate "Tapless"
cellgen select COMPLEX10
cellgen autoflow
export layout COMPLEX10 D:\AutoCellLibX\pySrc\outputs\adder/COMPLEX10.gds
exit

