set lpsolve "D:\AutoCellLibX\tools\gurobi_cl\gurobi_cl.cmd"
load technology "D:\AutoCellLibX\tools\astran\build\Work\tech_freePDK45.rul"
load netlist "D:\AutoCellLibX\pySrc\outputs\adder\COMPLEX9.sp"
set rowheight 13
set grid 0.2 0.2
set supplysize 0.72
set nwellpos 1.14
set celltemplate "Tapless"
cellgen select COMPLEX9
cellgen autoflow
export layout COMPLEX9 D:\AutoCellLibX\pySrc\outputs\adder/COMPLEX9.gds
exit

