set lpsolve "D:\AutoCellLibX\tools\gurobi_cl\gurobi_cl.cmd"
load technology "D:\AutoCellLibX\tools\astran\build\Work\tech_freePDK45.rul"
load netlist "../stdCelllib/cellsAstranFriendly.sp"
set rowheight 13
set grid 0.19 0.19
set supplysize 0.26
set nwellpos 1.235
set celltemplate "Tapless"
cellgen select OAI21X1
cellgen autoflow
export layout OAI21X1 D:\AutoCellLibX\pySrc\originalAstranStdCells/OAI21X1.gds
exit

