set lpsolve "D:\AutoCellLibX\tools\gurobi_cl\gurobi_cl.cmd"
load technology "D:\AutoCellLibX\tools\astran\build\Work\tech_freePDK45.rul"
load netlist "../stdCelllib/cellsAstranFriendly.sp"
set rowheight 13
set grid 0.2 0.2
set supplysize 0.72
set nwellpos 1.14
set celltemplate "Tapless"
cellgen select CLKBUF1
cellgen autoflow
export layout CLKBUF1 D:\AutoCellLibX\pySrc\originalAstranStdCells/CLKBUF1.gds
exit

